# run build when push files to react project
name: build react files
env:
    GENERATE_SOURCEMAP: false
    CI: false
on:
    push:
        paths-ignore:
            - 'posts/**'
            - 'build/**'
jobs:
    # use pnpm to build react files
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7.9.5
            - uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - name: Install Dependencies
              run: pnpm i
            - name: Build dist resources
              run: pnpm run build
    # deploy the build/ folder to github-pages branch
    depoly:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build
                  branch: github-pages
